### ISSUE TITLE
There was an error while parsing the InputStream

### ISSUE THREAD

**Issue by vanto** [bpelunit/bpelunit#7]
When I start a test suite or a single test from Eclipse, I frequently (but not deterministically) get the error message above and the test run does not start.

```
java.lang.RuntimeException: There was an error while parsing the InputStream
at org.apache.velocity.tools.config.XmlFactoryConfiguration.read(XmlFactoryConfiguration.java:132)
at org.apache.velocity.tools.config.FileFactoryConfiguration.read(FileFactoryConfiguration.java:140)
at org.apache.velocity.tools.config.FileFactoryConfiguration.read(FileFactoryConfiguration.java:116)
at org.apache.velocity.tools.config.FileFactoryConfiguration.read(FileFactoryConfiguration.java:91)
at org.apache.velocity.tools.config.FileFactoryConfiguration.read(FileFactoryConfiguration.java:69)
at org.apache.velocity.tools.config.FileFactoryConfiguration.read(FileFactoryConfiguration.java:59)
at org.apache.velocity.tools.config.ConfigurationUtils.getDefaultTools(ConfigurationUtils.java:79)
at org.apache.velocity.tools.config.ConfigurationUtils.getAutoLoaded(ConfigurationUtils.java:176)
at org.apache.velocity.tools.ToolManager.autoConfigure(ToolManager.java:74)
at org.apache.velocity.tools.ToolManager.<init>(ToolManager.java:68)
at org.apache.velocity.tools.ToolManager.<init>(ToolManager.java:54)
at net.bpelunit.framework.model.test.TestSuite.<init>(TestSuite.java:106)
at net.bpelunit.framework.SpecificationLoader.parseSuite(SpecificationLoader.java:247)
at net.bpelunit.framework.SpecificationLoader.loadTestSuite(SpecificationLoader.java:145)
at net.bpelunit.framework.BPELUnitRunner.loadTestSuite(BPELUnitRunner.java:233)
at net.bpelunit.framework.client.eclipse.launch.BPELLaunchConfigurationDelegate.launch(BPELLaunchConfigurationDelegate.java:110)
at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:853)
at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:702)
at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:924)
at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1128)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.ClassNotFoundException: org.apache.velocity.tools.config.Data
at org.apache.commons.digester.Digester.createSAXException(Digester.java:3181)
at org.apache.commons.digester.Digester.createSAXException(Digester.java:3207)
at org.apache.commons.digester.Digester.startElement(Digester.java:1456)
at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(Unknown Source)
at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
at org.apache.commons.digester.Digester.parse(Digester.java:1765)
at org.apache.velocity.tools.config.XmlFactoryConfiguration.read(XmlFactoryConfiguration.java:128)
... 20 more
Caused by: java.lang.ClassNotFoundException: org.apache.velocity.tools.config.Data
at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:244)
at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:230)
at org.apache.commons.digester.ObjectCreateRule.begin(ObjectCreateRule.java:205)
at org.apache.commons.digester.Rule.begin(Rule.java:175)
at org.apache.commons.digester.Digester.startElement(Digester.java:1453)
... 33 more
```

**Comment by dluebke** [comment]
I will try to reproduce this with the current 1.6.2-SNAPSHOT in Eclipse-based ActiveVOS Designer installation.

**Comment by bluezio** [comment]
Did you manage to reproduce this?

**Comment by dluebke** [comment]
Hi, I am trying to set-up a VM with ActiveVOS Designer 9. However, it is shipped as a 32bit Eclipse install and I have to fiddle a bit to get it working on a 64bit Kubuntu. :(
